### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by huntz20** [moduslabs/vue3-example-ssr#2]
Hi first thanks for a great tutorial 

i follow step from your youtube but my build failed 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/huntz/.nvm/versions/node/v12.18.3/bin/node',
1 verbose cli   '/home/huntz/.nvm/versions/node/v12.18.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ssr-example@0.1.0~prebuild: ssr-example@0.1.0
6 info lifecycle ssr-example@0.1.0~build: ssr-example@0.1.0
7 verbose lifecycle ssr-example@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ssr-example@0.1.0~build: PATH: /home/huntz/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/huntz/WebstormProjects/ssr-example/node_modules/.bin:/home/huntz/Android/Sdk/:/home/huntz/anaconda3/bin:/home/huntz/.kiex/bin:/home/huntz/.nvm/versions/node/v12.18.3/bin:/home/huntz/WebstormProjects/ssr-example/node_modules/.bin:/home/huntz/.cargo/bin:/home/huntz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/huntz/.dotnet/tools:/home/huntz/WebstormProjects/ssr-example/flutter/bin:/opt/yarn-1.22.5/bin
9 verbose lifecycle ssr-example@0.1.0~build: CWD: /home/huntz/WebstormProjects/ssr-example
10 silly lifecycle ssr-example@0.1.0~build: Args: [ '-c', 'vue-cli-service build' ]
11 silly lifecycle ssr-example@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle ssr-example@0.1.0~build: Failed to exec build script
13 verbose stack Error: ssr-example@0.1.0 build: `vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/huntz/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/huntz/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid ssr-example@0.1.0
15 verbose cwd /home/huntz/WebstormProjects/ssr-example
16 verbose Linux 5.4.0-53-generic
17 verbose argv "/home/huntz/.nvm/versions/node/v12.18.3/bin/node" "/home/huntz/.nvm/versions/node/v12.18.3/bin/npm" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error ssr-example@0.1.0 build: `vue-cli-service build`
22 error Exit status 1
23 error Failed at the ssr-example@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

i try to find where my mistake then i remove 
`webpackConfig.target("node")` it work 

can you explain me why that happen

**Comment by huntz20** [comment]
silly me i just need to install @vue/server-renderer
